'use strict';
const PLANET_SEARCH_REQUEST = 'PLANET_SEARCH_REQUEST';
const PLANET_SEARCH_SUCCESS = 'PLANET_SEARCH_SUCCESS';
const PLANET_SEARCH_FAILURE = 'PLANET_SEARCH_FAILURE';

export {
	PLANET_SEARCH_REQUEST,
	PLANET_SEARCH_SUCCESS,
	PLANET_SEARCH_FAILURE
}
